about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

foodgram/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

handler404 = 'foodgram.views.page_not_found'  # noqa
handler500 = 'foodgram.views.server_error'  # noqa

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),

    path('about/', include('about.urls', namespace='about')),

    path('', include('recipes.urls'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

templates/includes/follow_card.html
{% load static %}
{% load thumbnail %}
{% csrf_token %}

<div class="card-user" data-author="{{ author.id }}">
    <div class="card-user__header">
        <h2 class="card-user__title">{{ author }}</h2>
    </div>
    <div class="card-user__body">
        <ul class="card-user__items">
            {% with author.recipes.all as recipes %}
                {% for recipe in recipes|slice:3 %}
                    <li class="card-user__item">
                        <div class="recipe">
                            {% thumbnail recipe.image "72x72" crop="center" upscale=True as im %}
                                <img src="{{ im.url }}" alt="{{ recipe }}" class="recipe__image">
                            {% endthumbnail %}
                            <h3 class="recipe__title">{{ recipe }}</h3>
                            <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
                        </div>
                    </li>
                {% endfor %}
                {% if recipes.count > 3 %}
                    <li class="card-user__item">
                        <a href="{% url 'authors_recipes' author.username %}" class="card-user__link link">Еще рецепты...</a>
                    </li>
                {% endif %}
            {% endwith %}
        </ul>
    </div>
    <div class="card-user__footer">
        <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться</button>
    </div>
</div>

templates/includes/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'index' %}" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="{% url 'about:author' %}" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="{% url 'about:tech' %}" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

templates/includes/header.html
{% with url_name=request.resolver_match.url_name shop_list_count=user.users_shopping_lists.all.count %}
    <nav class="nav">
          <div class="nav__container container">
              <ul class="nav__items list">
                  <li class="nav__item {% if 'index' in url_name %}nav__item_active{% endif %}"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
                  <li class="nav__item {% if 'subscriptions_list' in url_name %}nav__item_active{% endif %}"><a href="{% url 'subscriptions_list' %}" class="nav__link link">Мои подписки</a></li>
                  <li class="nav__item {% if 'add_recipe' in url_name %}nav__item_active{% endif %}"><a href="{% url 'add_recipe' %}" class="nav__link link">Создать рецепт</a></li>
                  <li class="nav__item {% if 'favorite' in url_name %} nav__item_active {% endif %}"><a href="{% url 'favorite' %}" class="nav__link link">Избранное</a></li>
                  <li class="nav__item {% if 'shopping_list' in url_name %} nav__item_active {% endif %}">
                      <a href="{% url 'shopping_list' %}" class="nav__link link">Список покупок</a>
                      <span class="badge badge_style_blue nav__badge" id="counter">{{ shop_list_count }}</span>
                  </li>
              </ul>
              <ul class="nav__items list">
                  <li class="nav__item"><a href="{% url 'authors_recipes' user %}" class="nav__link link">{{ user.username }}</a></li>
                  <li class="nav__item"><a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
                  <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
              </ul>
          </div>
    </nav>
{% endwith %}

templates/includes/header_unreg.html
{% with request.resolver_match.url_name as url_name %}
    <nav class="nav">
        <div class="nav__container container">
            <ul class="nav__items list">
                <li class="nav__item {% if 'index' not in url_name %}nav__item_disabled{% endif %}"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
            </ul>
            <ul class="nav__items list">
                <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
                <li class="nav__item"><a href="{% url 'signup' %}" class="button button_style_blue">Создать аккаунт</a></li>
            </ul>
        </div>
    </nav>
{% endwith %}

templates/includes/index_style.html
{% load static %}
  <script src="{% static 'js/components/MainCards.js' %}"></script>

  <script src="{% static 'js/components/Purchases.js' %}"></script>
  <script src="{% static 'js/components/Favorites.js' %}"></script>

  <script src="{% static 'js/config/config.js' %}"></script>
  <script src="{% static 'js/components/CardList.js' %}"></script>
  <script src="{% static 'js/components/Header.js' %}"></script>

  <script src="{% static 'js/api/Api.js' %}"></script>
  <script src="{% static 'indexAuth.js' %}"></script>

templates/includes/paginator.html
<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">
        {% if items.has_previous %}
            <li class="pagination__item"><a class="pagination__link link" href="?page={{ items.previous_page_number }}"><span class="icon-left"></span></a></li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if items.number == i %}
                <li class="pagination__item pagination__item_active"><a class="pagination__link link">{{ i }}</a></li>
            {% else %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if items.has_next %}
            <li class="pagination__item"><a class="pagination__link link" href="?page={{ items.next_page_number }}"><span class="icon-right"></span></a></li>
        {% endif %}
    </ul>
</nav>

templates/includes/recipe_card.html
{% load static %}
{% load recipe_filters %}
{% csrf_token %}
<div class="card" data-id="{{ recipe.id }}">
    {% load thumbnail %}
    {% thumbnail recipe.image "480x480" crop="center" upscale=True as im %}
        <a href="{% url 'view_recipe' recipe.id %}" class="link" target="_blank"><img src="{{ im.url }}" alt="{{ recipe }}" class="card__image"></a>
    {% endthumbnail %}
    <div class="card__body">
        <a class="card__title link" href="{% url 'view_recipe' recipe.id %}" target="_blank">{{ recipe }}</a>
        <ul class="card__items">
            {% for tag in recipe.tags.all %}
                {% if tag.title == 'Обед' %}
                  <li class="card__item"><span class="badge badge_style_green">{{ tag.title }}</span></li>
                {% elif tag.title == 'Завтрак' %}
                   <li class="card__item"><span class="badge badge_style_orange">{{ tag.title }}</span></li>
                {% elif tag.title == 'Ужин' %}
                  <li class="card__item"><span class="badge badge_style_purple">{{ tag.title }}</span></li>
                {% endif %}
            {% endfor %}
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
            <p class="card__text"><span class="icon-user"></span> <a href="{% url 'authors_recipes' recipe.author.username %}" style="color: black">{{ recipe.author }}</a></p>
        </div>
    </div>
    <div class="card__footer">
        {% if user.is_authenticated %}
            {% if user.users_shopping_lists.all|favorite_recipe:recipe %}
                <button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span>Рецепт добавлен</button>
            {% else %}
                <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
            {% endif %}
            {% if user.favorite_recipes.all|favorite_recipe:recipe %}
                <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_active"></span></button>
            {% else %}
                <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>
            {% endif %}
        {% endif %}
    </div>
</div>

templates/includes/tags.html
{% load recipe_filters %}
{% with url_name=request.resolver_match.url_name %}
    <ul class="tags">
        {% for tag in tags %}
        <li class="tags__item">
            <a id="id_tags_{{ tag.id }}"
               class="tags__checkbox {{ tag.color }} {% if tag.id in tags_for_filter %} tags__checkbox_active{% endif %}"
                {% if author %}
                   href="{% url url_name author.username %}?{{ request|tags_link:tag }}"></a>
                {% else %}
                    href="{% url url_name %}?{{ request|tags_link:tag }}"></a>
                {% endif %}
            <span for="id_tags_{{tag.id}}"class="tags__label">{{ tag.title }}</span>
        </li>
        {% endfor %}
    </ul>
{% endwith %}