about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

foodgram/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

handler404 = 'foodgram.views.page_not_found'  # noqa
handler500 = 'foodgram.views.server_error'  # noqa

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),

    path('about/', include('about.urls', namespace='about')),

    path('', include('recipes.urls'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

recipes/urls.py
from django.urls import path

from recipes import views

urlpatterns = [
    path('', views.index, name='index'),

    path('recipe/<int:recipe_id>/', views.view_recipe, name='view_recipe'),
    path('recipe/new/', views.add_recipe, name='add_recipe'),
    path('recipe/<int:recipe_id>/edit/', views.edit_recipe,
         name='edit_recipe'),
    path('recipe/<int:recipe_id>/delete/', views.del_recipe,
         name='del_recipe'),
    path(
        'recipes/<str:username>/',
        views.authors_recipes,
        name='authors_recipes'
    ),

    path('favorite/', views.favorite, name='favorite'),
    path('favorites/<int:recipe_id>/', views.favorites, name='favorites'),

    path('subscriptions_list/', views.subscriptions_list,
         name='subscriptions_list'),
    path('subscriptions/<int:author_id>/', views.subscriptions,
         name='subscriptions'),

    path('purchases/<int:recipe_id>/', views.purchases, name='purchases'),
    path('shopping_list/', views.shopping_list, name='shopping_list'),
    path('shopping_list/save/', views.shopping_list_save,
         name='shopping_list_save'),

    path('ingredients/', views.ingredients, name='ingredients'),

]

recipes/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import UniqueConstraint

from .validate import user_directory_path, validate_image

User = get_user_model()


class Ingredient(models.Model):
    """Модель ингредиента."""
    title = models.CharField(max_length=200)
    dimension = models.CharField(max_length=50)

    class Meta:
        ordering = ('title',)
        verbose_name = 'Ингредиент'
        verbose_name_plural = 'Ингредиенты'

    def __str__(self):
        return self.title


class Tag(models.Model):
    """Модель тега."""
    ORANGE = 'tags__checkbox_style_orange'
    GREEN = 'tags__checkbox_style_green'
    PURPLE = 'tags__checkbox_style_purple'
    TAG_COLOR = (
        (ORANGE, 'Оранжевый',),
        (GREEN, 'Зеленый'),
        (PURPLE, 'Фиолетовый'),
    )
    title = models.CharField('Название', max_length=50, null=True)
    color = models.CharField('Цвет', max_length=50, choices=TAG_COLOR)

    class Meta:
        ordering = ('title',)
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    def __str__(self):
        return self.title


class Recipe(models.Model):
    """Модель рецепта."""
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='recipes',
        verbose_name='автор рецепта',
    )
    tags = models.ManyToManyField(Tag, related_name='recipes')
    title = models.CharField('название рецепта', max_length=256, blank=False)
    image = models.ImageField(
        upload_to=user_directory_path,
        validators=[validate_image],
        verbose_name='изображение',
        blank=True,
        null=True,
        default='default.jpg',
    )
    description = models.TextField('описание рецепта', blank=False)
    cooking_time = models.PositiveSmallIntegerField('время приготовления')
    ingredients = models.ManyToManyField(
        Ingredient,
        related_name='recipes',
        through='IngredientAmount',
        verbose_name='ингредиент',
    )
    pub_date = models.DateTimeField(
        'дата публикации', auto_now_add=True, db_index=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'

    def __str__(self):
        return self.title


class IngredientAmount(models.Model):
    """Количество ингредиента в рецепте."""
    ingredient = models.ForeignKey(
        Ingredient, on_delete=models.CASCADE, verbose_name='ингредиент',
        blank=False,
        related_name='recipes_amount',
    )
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name='ingredients_amount',
        blank=False,
        verbose_name='рецепт',
    )
    amount = models.IntegerField(
        'количество',
        blank=False,
        validators=[
            MinValueValidator(1)
        ]
    )

    class Meta:
        ordering = ('-recipe__pub_date',)
        verbose_name = 'Кол-во ингредиента'
        verbose_name_plural = 'Кол-во ингредиентов'

    def __str__(self):
        ingredient = self.ingredient.title
        amount = self.amount
        dimension = self.ingredient.dimension
        recipe = self.recipe
        return (f'{ingredient}: {amount}{dimension} - рецепт #{recipe.id}'
                f' {recipe.title}')


class FavoriteRecipe(models.Model):
    """Избранный рецепт."""
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='favorite_recipes'
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='at_favorites'
    )
    pub_date = models.DateTimeField(
        'дата добавления', auto_now_add=True, db_index=True
    )

    class Meta:
        ordering = ('-recipe__pub_date',)
        verbose_name = 'Избранный рецепт'
        verbose_name_plural = 'Избранные рецепты'

    def __str__(self):
        user_username = self.user.username
        recipe = self.recipe.title
        return f'{user_username} добавил в избранное {recipe}'


class ShoppingList(models.Model):
    """Список покупок."""
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='users_shopping_lists'
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='at_shopping_lists'
    )
    pub_date = models.DateTimeField(
        'дата добавления', auto_now_add=True, db_index=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Список покупок'
        verbose_name_plural = 'Списки покупок'

    def __str__(self):
        user_username = self.user.username
        recipe = self.recipe.title
        return f'{user_username} добавил в список покупок {recipe}'


class Follow(models.Model):
    """Подписка на автора."""
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following"
    )
    pub_date = models.DateTimeField('дата добавления', auto_now_add=True)

    class Meta:
        ordering = ('-pub_date',)
        constraints = [
            UniqueConstraint(
                fields=['user', 'author'],
                name='unique_following',
            ),
        ]
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self):
        user_username = self.user.username
        author_username = self.author.username
        return f'{user_username} подписался на {author_username}'

recipes/forms.py
from django import forms

from .models import Recipe


class RecipeForm(forms.ModelForm):
    """Форма создания рецепта."""

    class Meta:
        model = Recipe
        fields = ('title', 'cooking_time', 'description', 'image', 'tags',)
        widgets = {
            'tags': forms.CheckboxSelectMultiple(),
            'description': forms.Textarea(attrs={'class': 'form__textarea'}),
        }

recipes/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Sum, F
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods

from foodgram import settings
from .forms import RecipeForm
from .models import Ingredient, Recipe, FavoriteRecipe, Follow, ShoppingList
from .utils import (get_ingredients, add_ingredients_to_recipe, save_recipe,
                    get_tags_for_filter, ingredients_for_shopping_list)

User = get_user_model()

OBJECT_PER_PAGE = settings.OBJECT_PER_PAGE


@require_http_methods(['GET'])
def ingredients(request):
    """Вывод ингредиентов в форме."""
    query = (request.GET['query']).lower()
    ingredients_list = (
        Ingredient.objects.values(
            'title',
            'dimension',
        ).filter(title__icontains=query)
    )
    context = list(ingredients_list)
    return JsonResponse(context, safe=False)


def index(request):
    """Главная страница. Список всех рецептов."""
    tags, tags_for_filter = get_tags_for_filter(request)
    recipes = Recipe.objects.filter(tags__in=tags_for_filter).distinct()
    paginator = Paginator(recipes, OBJECT_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'page': page,
        'paginator': paginator,
        'tags': tags,
        'tags_for_filter': tags_for_filter,
    }
    return render(request, 'index.html', context)


def authors_recipes(request, username):
    """Список рецептов одного автора."""
    author = get_object_or_404(User, username=username)
    tags, tags_for_filter = get_tags_for_filter(request)
    recipe_list = Recipe.objects.filter(author=author,
                                        tags__in=tags_for_filter).distinct()
    paginator = Paginator(recipe_list, OBJECT_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'page': page,
        'paginator': paginator,
        'author': author,
        'tags': tags,
        'tags_for_filter': tags_for_filter,
    }
    if request.user.is_authenticated:
        my_user = request.user
        follow = Follow.objects.filter(user=my_user, author=author)
        follow_or_author = follow or my_user == author
        context['follow_or_author'] = follow_or_author
    return render(request, 'authors_recipes.html', context)


def view_recipe(request, recipe_id):
    """Просмотр одного рецепта."""
    recipe = get_object_or_404(Recipe, id=recipe_id)
    context = {
        'recipe': recipe,
    }
    return render(request, 'recipe_view.html', context)


@login_required
def add_recipe(request):
    """Создание нового рецепта."""
    form = RecipeForm(request.POST or None, files=request.FILES or None, )
    if form.is_valid():
        recipe = save_recipe(request, form)
        return redirect(to=view_recipe, recipe_id=recipe.id)
    context = {
        'form': form,
    }
    return render(request, 'recipe_form.html', context)


@login_required
def edit_recipe(request, recipe_id):
    """Редактировать рецепт."""
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if request.user != recipe.author and not request.user.is_staff:
        return redirect(to=view_recipe, recipe_id=recipe_id)

    form = RecipeForm(
        request.POST or None,
        files=request.FILES or None,
        instance=recipe
    )
    if form.is_valid():
        recipe.ingredients.clear()
        form.save()
        ingredients = get_ingredients(request)
        add_ingredients_to_recipe(ingredients, recipe)
        return redirect(to=view_recipe, recipe_id=recipe_id)
    context = {
        'form': form,
        'recipe': recipe,
    }
    return render(request, 'recipe_form.html', context)


@login_required
def del_recipe(request, recipe_id):
    """Удалить рецепт."""
    my_user = request.user
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if my_user != recipe.author and not my_user.is_staff:
        return redirect(to=view_recipe, recipe_id=recipe_id)
    recipe.delete()
    return redirect(to=index)


@login_required
def favorite(request):
    """Все избранные рецепты."""
    tags, tags_for_filter = get_tags_for_filter(request)
    my_user = request.user
    recipes_list = my_user.favorite_recipes.filter(
        recipe__tags__in=tags_for_filter).distinct()
    paginator = Paginator(recipes_list, OBJECT_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'page': page,
        'paginator': paginator,
        'tags': tags,
        'tags_for_filter': tags_for_filter,
    }
    return render(request, 'favorite.html', context)


@login_required
def subscriptions_list(request):
    """Страница из рецептов избранных авторов."""
    my_user = request.user
    following_authors = User.objects.filter(following__user=my_user)
    paginator = Paginator(following_authors, 3)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'page': page,
        'paginator': paginator
    }
    return render(request, 'subscriptions.html', context)


@login_required
@require_http_methods(['POST', 'DELETE'])
def favorites(request, recipe_id):
    """Добавить/удалить рецепт в избранное."""
    my_user = request.user
    recipe = get_object_or_404(Recipe, id=recipe_id)
    context = {'success': True}

    if request.method == 'POST':
        _, created = FavoriteRecipe.objects.get_or_create(user=my_user,
                                                          recipe=recipe)
        return JsonResponse(context)

    favorite_recipe = get_object_or_404(FavoriteRecipe, user=my_user,
                                        recipe__id=recipe_id)
    favorite_recipe.delete()
    return JsonResponse(context)


@login_required
@require_http_methods(['POST', 'DELETE'])
def subscriptions(request, author_id):
    """Подписаться/Отписаться на Автора."""
    my_user = request.user
    author = get_object_or_404(User, id=author_id)
    context = {'success': True}
    if request.method == 'POST':
        _, created = Follow.objects.get_or_create(user=my_user, author=author)
        return JsonResponse(context)

    subscription = Follow.objects.filter(user=my_user, author=author)
    if subscription.exists():
        subscription.delete()
    return JsonResponse(context)


@login_required
@require_http_methods(['POST', 'DELETE'])
def purchases(request, recipe_id):
    """Добавить/удалить в список покупок."""
    my_user = request.user
    recipe = get_object_or_404(Recipe, id=recipe_id)
    context = {'success': True}
    if request.method == 'POST':
        _, created = ShoppingList.objects.get_or_create(user=my_user,
                                                        recipe=recipe)
        return JsonResponse(context)

    favorite_recipe = get_object_or_404(ShoppingList, user=my_user,
                                        recipe=recipe)
    favorite_recipe.delete()
    return JsonResponse(context)


@login_required
def shopping_list(request):
    """Страница Список покупок."""
    my_user = request.user
    shopping_list = my_user.users_shopping_lists.all()
    context = {
        'shopping_list': shopping_list,
    }
    return render(request, 'shopping_list.html', context)


@login_required
def shopping_list_save(request):
    """Скачать список ингредиентов."""
    my_user = request.user
    ingredient_list = Recipe.objects.prefetch_related(
        'ingredients', 'ingredients_amount'
    ).filter(
        at_shopping_lists__user=my_user
    ).order_by(
        'ingredients__title'
    ).values(
        'ingredients__title', 'ingredients__dimension'
    ).annotate(
        title=F('ingredients__title'),
        amount=Sum('ingredients_amount__amount'),
        dimension=F('ingredients__dimension')
    )

    ingredient_txt = ingredients_for_shopping_list(ingredient_list)

    filename = 'shoppinglist.txt'
    response = HttpResponse(ingredient_txt, content_type='text/plain')
    response['Content-Disposition'] = f'attachment; filename={filename}'
    return response

templates/authors_recipes.html
{% extends "base.html" %}
{% load static %}
{% load recipe_filters %}
{% block title %}Рецепты{% endblock %}

{% block main_title %}{{ author.username }}{% endblock main_title %}
{% block tags %}{% include 'includes/tags.html' %}{% endblock tags %}

{% block content %}
{% csrf_token %}
    {% if user.is_authenticated and user != author %}
        <div class="author-subscribe" data-author="{{ author.id }}">
            <p style="padding: 0 0 2em 0;">
                {% if not follow_or_author %}
                    <button class="button button_style_light-blue button_size_subscribe"
                            name="subscribe" data-out>Подписаться на автора
                    </button>
                {% else %}
                    <button class="button button_style_light-blue button_size_subscribe"
                            name="subscribe">Отписаться от автора
                    </button>
                {% endif %}
            </p>
        </div>
    {% endif %}
    <div class="card-list">
        {% for recipe in page %}
            {% include 'includes/recipe_card.html' with recipe=recipe %}
        {% endfor %}
    </div>
        {% if page.has_other_pages %}
            {% include "includes/paginator.html" with items=page paginator=paginator %}
        {% endif %}

{% endblock content %}

{% block js %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>

    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>

    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>

    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'authorRecipe.js' %}"></script>
{% endblock js %}

templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Заголовок{% endblock %}</title>
    {% load static %}
    {% block css %}<link rel="stylesheet" href="{% static 'pages/index.css' %}">{% endblock css %}
</head>
<body class="body">
    <header class="header">
        {% if user.is_authenticated %}
            {% include 'includes/header.html' %}
        {% else %}
            {% include 'includes/header_unreg.html' %}
        {% endif %}
    </header>
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">{% block main_title %}{% endblock main_title %}</h1>
            {% block tags %}{% endblock tags %}
        </div>
        {% block content %}
        <!-- Содержимое страницы -->
        {% endblock %}
    </main>
    {% include 'includes/footer.html' %}
    {% block js %}

    {% endblock js %}
</body>
</html>

templates/favorite.html
{% extends "base.html" %}
{% load static %}
{% load recipe_filters %}
{% block title %}Рецепты{% endblock %}

{% block main_title %}Избранное{% endblock main_title %}
{% block tags %}{% include 'includes/tags.html' %}{% endblock tags %}

{% block content %}
    <div class="card-list">
        {% for item in page %}
            {% include 'includes/recipe_card.html' with recipe=item.recipe %}
        {% endfor %}
    </div>
        {% if page.has_other_pages %}
            {% include "includes/paginator.html" with items=page paginator=paginator %}
        {% endif %}

{% endblock content %}

{% block js %}
  <script src="{% static 'js/components/MainCards.js' %}"></script>

  <script src="{% static 'js/components/Purchases.js' %}"></script>
  <script src="{% static 'js/components/Favorites.js' %}"></script>

  <script src="{% static 'js/config/config.js' %}"></script>
  <script src="{% static 'js/components/CardList.js' %}"></script>
  <script src="{% static 'js/components/Header.js' %}"></script>

  <script src="{% static 'js/api/Api.js' %}"></script>
  <script src="{% static 'favorite.js' %}"></script>
{% endblock js %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load recipe_filters %}
{% block title %}Рецепты{% endblock %}

{% block main_title %}Рецепты{% endblock main_title %}
{% block tags %}{% include 'includes/tags.html' %}{% endblock tags %}

{% block content %}

    <div class="card-list">
        {% for recipe in page %}
            {% include 'includes/recipe_card.html' with recipe=recipe %}
        {% endfor %}
    </div>
        {% if page.has_other_pages %}
            {% include "includes/paginator.html" with items=page paginator=paginator %}
        {% endif %}

{% endblock content %}

{% block js %}
  <script src="{% static 'js/components/MainCards.js' %}"></script>

  <script src="{% static 'js/components/Purchases.js' %}"></script>
  <script src="{% static 'js/components/Favorites.js' %}"></script>

  <script src="{% static 'js/config/config.js' %}"></script>
  <script src="{% static 'js/components/CardList.js' %}"></script>
  <script src="{% static 'js/components/Header.js' %}"></script>

  <script src="{% static 'js/api/Api.js' %}"></script>
  <script src="{% static 'indexAuth.js' %}"></script>
{% endblock js %}

templates/recipe_form.html
{% extends "base.html" %}
{% load static %}
{% load recipe_filters %}

{% block title %}
    {% if not recipe %}Создание рецепта{% else %}Редактирование рецепта{% endif %}
{% endblock title %}


{% block css %}<link rel="stylesheet" href="{% static 'pages/form.css' %}">{% endblock css %}

{% block main_title %}
    {% if not recipe %}Создание рецепта{% else %}Редактирование рецепта{% endif %}
{% endblock main_title %}

{% block content %}

    <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- Название рецепта -->
            <div class="form__group">
                <label for="id_name" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    {{ form.title|addclass:"form__input" }}
                    <span class="form__error">{{ form.title.errors }}</span>
                </div>
            </div>
            <!-- Теги -->
            <div class="form__group">
                <p class="form__label">Теги</p>
                 <div class="form__field-group">
                    <div class="tags">
                        {% for tag in form.fields.tags.choices.queryset %}
                            <div class="tags__item">
                                <input type="checkbox"
                                       name="tags"
                                       value="{{ tag.id }}"
                                       id="id_{{ tag.value }}"
                                       class="tags__checkbox {{tag.color}}"
                                       {% if tag in recipe.tags.all %}checked{% endif %}>
                                <label for="{{ tag.id }}" class="tags__label">{{ tag }}</label>
                            </div>
                        {% endfor %}
                        <span class="form__error">{{ form.tags.errors }}</span>
                    </div>
                 </div>
            </div>
            <!-- Ингредиенты -->
            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="1">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container">
                        {% if recipe %}
                            {% for item in recipe.ingredients_amount.all %}
                                <div class="form__field-item-ingredient" id="ing_{{ forloop.counter }}">
                                    <span> {{ item.ingredient.title }} {% if item.amount > 0 %}{{ item.amount|floatformat }}{% endif %} {{ item.ingredient.dimension }}.</span>
                                    <span class="form__field-item-delete"></span>
                                    <input id="nameIngredient_{{ forloop.counter }}" name="nameIngredient_{{ forloop.counter }}" type="hidden" value="{{ item.ingredient.title }}">
                                    <input id="valueIngredient_{{ forloop.counter }}" name="valueIngredient_{{ forloop.counter }}" type="hidden" value="{{ item.amount }}">
                                    <input id="unitsIngredient_{{ forloop.counter }}" name="unitsIngredient_{{ forloop.counter }}" type="hidden" value="{{ item.ingredient.dimension }}">
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    <span class="form__error"></span>
                </div>
            </div>
            <!-- Время приготовления -->
            <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    <input type="text"
                           id="{{ form.cooking_time.id_for_label }}"
                           name="{{ form.cooking_time.html_name }}"
                           value="1"
                           class="form__input">
                    <label for="id_time" class="form__label">минут</label>
                    <span class="form__error">{{ form.cooking_time.errors }}</span>
                </div>
            </div>
            <!-- Описание рецепта -->
            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    {{ form.description }}
                    <span class="form__error">{{ form.description.errors }}</span>
                </div>
            </div>
            <!-- Загрузить фото -->
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                   {{ form.image }}
                    <span class="form__error">{{ form.image.errors }}</span>
                </div>
            </div>
            <!-- Кнопка -->
            <div class="form__footer">
                {% if recipe %}
                    <button class="button button_style_blue">Сохранить</button> <a style="margin-left: 2.5em" href="{% url 'del_recipe' recipe.id %}" class="form__ingredient-link">Удалить</a>
                {% else %}
                    <button class="button button_style_blue">Создать рецепт</button>
                {% endif %}
            </div>
        </form>
    </div>

{% endblock content %}

{% block js %}
  <script src="{% static 'js/config/config.js' %}"></script>
  <script src="{% static 'js/components/Header.js' %}"></script>
  <script src="{% static 'js/utils/debouncing.js' %}"></script>

  <script src="{% static 'js/api/Api.js' %}"></script>
  <script src="{% static 'formRecipe.js' %}"></script>
{% endblock js %}

templates/shopping_list.html
{% extends "base.html" %}
{% load static %}
{% load recipe_filters %}
{% load thumbnail %}

{% block title %}Список покупок{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'pages/shopList.css' %}">{% endblock css %}


{% block main_title %}
    {% with shop_list_count=user.users_shopping_lists.all.count %}
        {% if shop_list_count > 0 %}
            Список покупок
        {% else %}
            Список покупок пуст
        {% endif %}
    {% endwith %}
{% endblock main_title %}



{% block content %}
{% csrf_token %}

    {% with shop_list_count=user.users_shopping_lists.all.count %}
        {% if shop_list_count > 0 %}
            <div class="card-list card-list_column">
                <ul class="shopping-list">
                    {% for purchase in shopping_list %}
                        <li class="shopping-list__item" data-id="{{ purchase.recipe.id }}">
                            <div class="recipe recipe_reverse">
                                {% thumbnail purchase.recipe.image "90x90" crop="center" upscale=True as im %}
                                    <img src="{{ im.url }}" alt="{{ purchase.recipe }}" class="recipe__image recipe__image_big">
                                {% endthumbnail %}
                                <h3 class="recipe__title">{{ purchase.recipe }}</h3>
                                <p class="recipe__text"><span class="icon-time"></span> {{ purchase.recipe.cooking_time }} мин.</p>
                            </div>
                            <a href="" class="shopping-list__button link">Удалить</a>
                        </li>
                    {% endfor %}
                </ul>
                <a href="{% url 'shopping_list_save' %}"><button class="button button_style_blue">Скачать список</button></a>
            </div>
        {% else %}
            <div class="card-list card-list_column">
                <ul class="shopping-list">
                    <li class="shopping-list__item">
                        <div class="recipe recipe_reverse">
                            <h3 class="recipe__title" style="max-width: 400px">Вы не добавили рецепт для списка покупок</h3>
                        </div>
                    </li>
                </ul>
            </div>
        {% endif %}
    {% endwith %}

{% endblock content %}

{% block js %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/components/ShopList.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'shopList.js' %}"></script>
{% endblock js %}